// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1) {
  return window['go']['main']['ToDoApp']['AddTask'](arg1);
}

export function GetTasks() {
  return window['go']['main']['ToDoApp']['GetTasks']();
}

export function RemoveTask(arg1) {
  return window['go']['main']['ToDoApp']['RemoveTask'](arg1);
}

export function ToggleTask(arg1) {
  return window['go']['main']['ToDoApp']['ToggleTask'](arg1);
}
